# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/core33g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/core33g/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/core33g/proprietary/bin/atrace:system/bin/atrace \
    vendor/samsung/core33g/proprietary/bin/calibration_init:system/bin/calibration_init \
    vendor/samsung/core33g/proprietary/bin/cpu:system/bin/cpu \
    vendor/samsung/core33g/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/core33g/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/core33g/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/core33g/proprietary/bin/modemd:system/bin/modemd \
    vendor/samsung/core33g/proprietary/bin/nandread:system/bin/nandread \
    vendor/samsung/core33g/proprietary/bin/npsmobex:system/bin/npsmobex \
    vendor/samsung/core33g/proprietary/bin/nvitemd:system/bin/nvitemd \
    vendor/samsung/core33g/proprietary/bin/phoneserver:system/bin/phoneserver \
    vendor/samsung/core33g/proprietary/bin/prepare_param.sh:system/bin/prepare_param.sh \
    vendor/samsung/core33g/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/core33g/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/core33g/proprietary/etc/gps.xml:system/etc/gps.xml \
    vendor/samsung/core33g/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/core33g/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/core33g/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/core33g/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/core33g/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/core33g/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/core33g/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/core33g/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/samsung/core33g/proprietary/lib/libatchannel.so:system/lib/libatchannel.so \
    vendor/samsung/core33g/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/core33g/proprietary/lib/libaudiopolicy_sec.so:system/lib/libaudiopolicy_sec.so \
    vendor/samsung/core33g/proprietary/lib/libbt-aptx-4.0.3.so:system/lib/libbt-aptx-4.0.3.so \
    vendor/samsung/core33g/proprietary/lib/libbt-codec.so:system/lib/libbt-codec.so \
    vendor/samsung/core33g/proprietary/lib/libbt-codec_aptx.so:system/lib/libbt-codec_aptx.so \
    vendor/samsung/core33g/proprietary/lib/libcontrolcsc.so:system/lib/libcontrolcsc.so \
    vendor/samsung/core33g/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/samsung/core33g/proprietary/lib/libmtp.so:system/lib/libmtp.so \
    vendor/samsung/core33g/proprietary/lib/libmtp_samsung.so:system/lib/libmtp_samsung.so \
    vendor/samsung/core33g/proprietary/lib/libmtp_samsung_jni.so:system/lib/libmtp_samsung_jni.so \
    vendor/samsung/core33g/proprietary/lib/libnvaccessor_fb.so:system/lib/libnvaccessor_fb.so \
    vendor/samsung/core33g/proprietary/lib/libnvexchange.so:system/lib/libnvexchange.so \
    vendor/samsung/core33g/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/core33g/proprietary/lib/libomx_aacdec_sprd.so:system/lib/libomx_aacdec_sprd.so \
    vendor/samsung/core33g/proprietary/lib/libomx_apedec_sprd.so:system/lib/libomx_apedec_sprd.so \
    vendor/samsung/core33g/proprietary/lib/libomx_avcdec_hw_sprd.so:system/lib/libomx_avcdec_hw_sprd.so \
    vendor/samsung/core33g/proprietary/lib/libomx_avcdec_sw_sprd.so:system/lib/libomx_avcdec_sw_sprd.so \
    vendor/samsung/core33g/proprietary/lib/libomx_avcenc_hw_sprd.so:system/lib/libomx_avcenc_hw_sprd.so \
    vendor/samsung/core33g/proprietary/lib/libomx_m4vh263dec_hw_sprd.so:system/lib/libomx_m4vh263dec_hw_sprd.so \
    vendor/samsung/core33g/proprietary/lib/libomx_m4vh263dec_sw_sprd.so:system/lib/libomx_m4vh263dec_sw_sprd.so \
    vendor/samsung/core33g/proprietary/lib/libomx_m4vh263enc_hw_sprd.so:system/lib/libomx_m4vh263enc_hw_sprd.so \
    vendor/samsung/core33g/proprietary/lib/libomx_mp3dec_sprd.so:system/lib/libomx_mp3dec_sprd.so \
    vendor/samsung/core33g/proprietary/lib/libomx_vpxdec_hw_sprd.so:system/lib/libomx_vpxdec_hw_sprd.so \
    vendor/samsung/core33g/proprietary/lib/librectifier.so:system/lib/librectifier.so \
    vendor/samsung/core33g/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/core33g/proprietary/lib/libreference-ril_sp.so:system/lib/libreference-ril_sp.so \
    vendor/samsung/core33g/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/core33g/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/core33g/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/core33g/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/core33g/proprietary/lib/libsamsungeffect.so:system/lib/libsamsungeffect.so \
    vendor/samsung/core33g/proprietary/lib/libseccamera_jni.so:system/lib/libseccamera_jni.so \
    vendor/samsung/core33g/proprietary/lib/libseccameracore.so:system/lib/libseccameracore.so \
    vendor/samsung/core33g/proprietary/lib/libsecface.so:system/lib/libsecface.so \
    vendor/samsung/core33g/proprietary/lib/libsecmediarecorder_jni.so:system/lib/libsecmediarecorder_jni.so \
    vendor/samsung/core33g/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/core33g/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/core33g/proprietary/lib/libstagefright_sprd_aacdec.so:system/lib/libstagefright_sprd_aacdec.so \
    vendor/samsung/core33g/proprietary/lib/libstagefright_sprd_h264dec.so:system/lib/libstagefright_sprd_h264dec.so \
    vendor/samsung/core33g/proprietary/lib/libstagefright_sprd_h264enc.so:system/lib/libstagefright_sprd_h264enc.so \
    vendor/samsung/core33g/proprietary/lib/libstagefright_sprd_mp3dec.so:system/lib/libstagefright_sprd_mp3dec.so \
    vendor/samsung/core33g/proprietary/lib/libstagefright_sprd_mpeg4dec.so:system/lib/libstagefright_sprd_mpeg4dec.so \
    vendor/samsung/core33g/proprietary/lib/libstagefright_sprd_mpeg4enc.so:system/lib/libstagefright_sprd_mpeg4enc.so \
    vendor/samsung/core33g/proprietary/lib/libstagefright_sprd_soft_h264dec.so:system/lib/libstagefright_sprd_soft_h264dec.so \
    vendor/samsung/core33g/proprietary/lib/libstagefright_sprd_soft_mpeg4dec.so:system/lib/libstagefright_sprd_soft_mpeg4dec.so \
    vendor/samsung/core33g/proprietary/lib/libstagefright_sprd_vpxdec.so:system/lib/libstagefright_sprd_vpxdec.so \
    vendor/samsung/core33g/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/core33g/proprietary/lib/libvbeffect.so:system/lib/libvbeffect.so \
    vendor/samsung/core33g/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
    vendor/samsung/core33g/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/core33g/proprietary/lib/hw/audio.primary.sc8830.so:system/lib/hw/audio.primary.sc8830.so \
    vendor/samsung/core33g/proprietary/lib/hw/audio_policy.sc8830.so:system/lib/hw/audio_policy.sc8830.so\
    vendor/samsung/core33g/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so \
    vendor/samsung/core33g/proprietary/lib/hw/gralloc.sc8830.so:system/lib/hw/gralloc.sc8830.so \
    vendor/samsung/core33g/proprietary/lib/hw/hwcomposer.sc8830.so:system/lib/hw/hwcomposer.sc8830.so \
    vendor/samsung/core33g/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
    vendor/samsung/core33g/proprietary/lib/hw/sprd_gsp.sc8830.so:system/lib/hw/sprd_gsp.sc8830.so \
    vendor/samsung/core33g/proprietary/lib/modules/autotst.ko:system/lib/modules/autotst.ko \
    vendor/samsung/core33g/proprietary/lib/modules/mali.ko:system/lib/modules/mali.ko \
    vendor/samsung/core33g/proprietary/lib/modules/mmc_test.ko:system/lib/modules/mmc_test.ko \
    vendor/samsung/core33g/proprietary/usr/idc/Synaptics_HID_TouchPad.idc:system/usr/idc/Synaptics_HID_TouchPad.idc \
    vendor/samsung/core33g/proprietary/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf \
    vendor/samsung/core33g/proprietary/vendor/firmware/BCM4343A0_001.001.034.0056.0197_M_ORC_Core3.hcd:system/vendor/firmware/BCM4343A0_001.001.034.0056.0197_M_ORC_Core3.hcd \
    vendor/samsung/core33g/proprietary/vendor/firmware/vbc_eq:system/vendor/firmware/vbc_eq \
    vendor/samsung/core33g/proprietary/vendor/lib/hw/lights.sc8830.so:system/vendor/lib/hw/lights.sc8830.so
